steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', '${_IMAGE_NAME}', '-f', 'Dockerfile.prod', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', '${_IMAGE_NAME}']

substitutions:
  _IMAGE_NAME: 'us-east1-docker.pkg.dev/hthaogcrj-practice/repo-for-job-1/job-1-image:latest'