research_task:
  description: >
    Conduct a thorough research about AI/ML advancements in the InsurTech space across the websites provided.
    
    - Insurtech Insights (https://www.insurtechinsights.com/news-insights/artificial-intelligence/)
    - InsurTech News (https://insurtechnews.com/)
    - InsurTech Digital (https://insurtechdigital.com/)
    
    Make sure you find any interesting and relevant information given the current date is { current_date }.
  expected_output: >
    A list with 5 bullet points representing the most important AI/ML advancements that have recently taken place
    in the InsurTech space. Include detailed sources and citations for each bulletpoint in your report so that the information
    can be verified. Include links to the sources in the final output.