name: Build and Deploy to Cloud Run Job

on:
  push:
    branches: ["main"]

env:
  PROJECT_ID: {{ vars.PROJECT_ID }} # Google Cloud project id
  PROJECT_NUMBER: {{ vars.PROJECT_NUMBER }} # Google Cloud project number
  JOB_NAME: {{ vars.JOB_NAME }} # Cloud Run Job name
  CLOUD_RUN_REGION: {{ vars.CLOUD_RUN_REGION }} # Cloud Run region
  DOCKER_IMAGE_URL: {{ vars.DOCKER_IMAGE_URL }} # Docker image URL
  ARTIFACTORY_URL: {{ vars.ARTIFACTORY_URL }} # Artifactory URL

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Google Cloud Auth
        uses: "google-github-actions/auth@v2"
        with:
          credentials_json: "${{ secrets.GCP_SA_KEY }}"
          project_id: ${{ env.PROJECT_ID }}

      - name: Configure Docker
        run: |
          gcloud auth configure-docker ${{ env.ARTIFACTORY_URL }}

      - name: Set Docker Image Tag
        run: echo "IMAGE_TAG=latest" >> $GITHUB_ENV

      - name: Build and Push Container
        run: |-
          docker build -f Dockerfile.prod -t "${{ env.DOCKER_IMAGE_URL }}:${{ env.IMAGE_TAG }}" ./
          docker push "${{ env.DOCKER_IMAGE_URL }}:${{ env.IMAGE_TAG }}"

      - name: Deploy to Cloud Run Job
        run: |
          gcloud run jobs deploy ${{ env.JOB_NAME }} \
          --image ${{ env.DOCKER_IMAGE_URL }}:${{ env.IMAGE_TAG }} \
          --region ${{ env.CLOUD_RUN_REGION }} \
          --project ${{ env.PROJECT_ID }}
